import type { MlbGameDetailView } from "./types";

export const mlbLiveDetail: MlbGameDetailView = {
  mlbGamePk: "824971",
  league: "mlb",
  status: "live",
  statusLabel: "Top 3rd",
  gameDate: "2026-08-02",
  gameDateLabel: "Today",
  venue: "Fenway Park",
  away: {
    id: "111",
    abbrev: "BOS",
    name: "Boston Red Sox",
    score: 2,
    record: null,
    last10: null,
    color: "#BD3039",
    logoUrl: null,
  },
  home: {
    id: "119",
    abbrev: "LAD",
    name: "Los Angeles Dodgers",
    score: 1,
    record: null,
    last10: null,
    color: "#005A9C",
    logoUrl: null,
  },
  decisions: null,
  linescore: {
    currentInning: 3,
    inningHalf: "top",
    innings: [
      { num: 1, awayRuns: 0, homeRuns: 1 },
      { num: 2, awayRuns: 1, homeRuns: 0 },
      { num: 3, awayRuns: 1, homeRuns: null },
    ],
    away: { runs: 2, hits: 3, errors: 0 },
    home: { runs: 1, hits: 2, errors: 1 },
  },
  situation: {
    balls: 2,
    strikes: 1,
    outs: 1,
    runners: { first: true, second: false, third: false },
    pitches: [
      {
        number: 1,
        type: "FF",
        mph: 95.2,
        result: "Ball",
        isStrike: false,
        zoneX: 0.1,
        zoneY: 0.2,
      },
      {
        number: 2,
        type: "SL",
        mph: 86.1,
        result: "Called Strike",
        isStrike: true,
        zoneX: -0.05,
        zoneY: 0.1,
      },
    ],
    atBat: {
      name: "Mookie Betts",
      hand: "RHB",
      summary: ".280 · 0-0 today",
    },
    onDeck: {
      name: "Freddie Freeman",
      hand: "LHB",
      summary: ".264",
    },
    pitching: {
      name: "Chris Sale",
      hand: "LHP",
      summary: "6 P · 0.1 IP, 0 ER, 6 K, 0 BB",
    },
    latestPlayText: "Ball",
  },
  plays: [
    {
      id: "p1",
      inning: 2,
      half: "bottom",
      text: "Ohtani grounds out",
      event: "Groundout",
      scoring: false,
      awayScore: 1,
      homeScore: 1,
      exitVelo: null,
      launchAngle: null,
      totalDistance: null,
      scoringTeam: null,
    },
    {
      id: "p2",
      inning: 3,
      half: "top",
      text: "Betts singles",
      event: "Single",
      scoring: false,
      awayScore: 2,
      homeScore: 1,
      exitVelo: null,
      launchAngle: null,
      totalDistance: null,
      scoringTeam: null,
    },
    {
      id: "p3",
      inning: 3,
      half: "top",
      text: "Freeman walks",
      event: "Walk",
      scoring: false,
      awayScore: 2,
      homeScore: 1,
      exitVelo: null,
      launchAngle: null,
      totalDistance: null,
      scoringTeam: null,
    },
  ],
  scoringPlays: [
    {
      id: "s1",
      inning: 1,
      half: "bottom",
      text: "Freeman homers (1)",
      event: "HR",
      scoring: true,
      awayScore: 0,
      homeScore: 1,
      exitVelo: null,
      launchAngle: null,
      totalDistance: null,
      scoringTeam: "home",
    },
    {
      id: "s2",
      inning: 2,
      half: "top",
      text: "Devers doubles, Betts scores",
      event: "2B",
      scoring: true,
      awayScore: 1,
      homeScore: 1,
      exitVelo: null,
      launchAngle: null,
      totalDistance: null,
      scoringTeam: "away",
    },
  ],
  boxScore: {
    awayBatters: [
      {
        name: "Betts",
        position: "RF",
        order: 1,
        ab: 2,
        r: 1,
        h: 1,
        rbi: 0,
        bb: 0,
        so: 0,
        hr: 1,
        sb: 0,
      },
    ],
    homeBatters: [
      {
        name: "Freeman",
        position: "1B",
        order: 3,
        ab: 2,
        r: 1,
        h: 1,
        rbi: 1,
        bb: 0,
        so: 0,
        hr: 1,
        sb: 0,
      },
    ],
    awayPitchers: [],
    homePitchers: [
      {
        name: "Sale",
        ip: "2.1",
        h: 3,
        r: 2,
        er: 2,
        bb: 1,
        k: 3,
        pitches: 42,
        hr: 1,
        era: "3.10",
        decision: null,
        strikes: 28,
        groundOuts: 2,
        flyOuts: 1,
        battersFaced: 12,
        inheritedRunners: 0,
        inheritedRunnersScored: 0,
      },
    ],
    awayBattingNotes: [],
    homeBattingNotes: [],
    awayBaserunningNotes: [],
    homeBaserunningNotes: [],
    awayFieldingNotes: [],
    homeFieldingNotes: [],
    awayPitchingTotals: null,
    homePitchingTotals: null,
  },
  teamStats: {
    away: {
      avg: ".252",
      obp: ".318",
      slg: ".405",
      hr: 0,
      r: 2,
      h: 3,
      k: 4,
      sb: 0,
      lob: 3,
      era: "3.10",
    },
    home: {
      avg: ".265",
      obp: ".330",
      slg: ".430",
      hr: 1,
      r: 1,
      h: 2,
      k: 3,
      sb: 0,
      lob: 2,
      era: "4.20",
    },
  },
  winProbability: {
    awayAbbrev: "BOS",
    homeAbbrev: "LAD",
    points: [{ playId: "p2", label: "Top 3", homeWinPct: 0.48 }],
    stakes: { label: "On this pitch", homeWinDelta: -2.1 },
  },
  hitChart: [],
  sources: ["statsapi", "espn"],
  fetchedAt: "2026-08-02T00:00:00Z",
};

export const mlbFinalDetail: MlbGameDetailView = {
  mlbGamePk: "776543",
  league: "mlb",
  status: "final",
  statusLabel: "Final",
  gameDate: "2026-08-02",
  gameDateLabel: "Today",
  venue: "Chase Field",
  away: {
    id: "109",
    abbrev: "ARI",
    name: "Arizona Diamondbacks",
    score: 4,
    record: "58-55",
    last10: null,
    color: "#A71930",
    logoUrl: null,
  },
  home: {
    id: "119",
    abbrev: "LAD",
    name: "Los Angeles Dodgers",
    score: 5,
    record: "62-51",
    last10: null,
    color: "#005A9C",
    logoUrl: null,
  },
  decisions: {
    winner: "Brandon Pfaadt",
    loser: "Walker Buehler",
    save: "Kevin Ginkel",
  },
  linescore: {
    currentInning: 9,
    inningHalf: null,
    innings: [
      { num: 1, awayRuns: 0, homeRuns: 1 },
      { num: 2, awayRuns: 2, homeRuns: 0 },
      { num: 3, awayRuns: 0, homeRuns: 0 },
      { num: 4, awayRuns: 1, homeRuns: 1 },
      { num: 5, awayRuns: 0, homeRuns: 0 },
      { num: 6, awayRuns: 1, homeRuns: 0 },
      { num: 7, awayRuns: 0, homeRuns: 1 },
      { num: 8, awayRuns: 0, homeRuns: 1 },
      { num: 9, awayRuns: 0, homeRuns: 1 },
    ],
    away: { runs: 4, hits: 8, errors: 1 },
    home: { runs: 5, hits: 9, errors: 0 },
  },
  situation: null,
  plays: [
    {
      id: "p-final",
      inning: 9,
      half: "bottom",
      text: "Freeman homers (2)",
      event: "Home Run",
      scoring: true,
      awayScore: 4,
      homeScore: 5,
      exitVelo: 104.1,
      launchAngle: 28.5,
      totalDistance: 412,
      scoringTeam: "home",
    },
  ],
  scoringPlays: [
    {
      id: "p-final",
      inning: 9,
      half: "bottom",
      text: "Freeman homers (2)",
      event: "Home Run",
      scoring: true,
      awayScore: 4,
      homeScore: 5,
      exitVelo: 104.1,
      launchAngle: 28.5,
      totalDistance: 412,
      scoringTeam: "home",
    },
  ],
  boxScore: {
    awayBatters: [
      {
        name: "Carroll",
        position: "LF",
        order: 1,
        ab: 4,
        r: 1,
        h: 2,
        rbi: 0,
        bb: 0,
        so: 1,
        hr: 0,
        sb: 1,
      },
    ],
    homeBatters: [
      {
        name: "Freeman",
        position: "1B",
        order: 3,
        ab: 4,
        r: 2,
        h: 2,
        rbi: 2,
        bb: 0,
        so: 0,
        hr: 2,
        sb: 0,
      },
    ],
    awayPitchers: [
      {
        name: "Buehler",
        ip: "5.0",
        h: 6,
        r: 4,
        er: 4,
        bb: 2,
        k: 5,
        pitches: 88,
        hr: 1,
        era: "4.50",
        decision: "(L, 8-5)",
        strikes: 55,
        groundOuts: 4,
        flyOuts: 3,
        battersFaced: 22,
        inheritedRunners: 0,
        inheritedRunnersScored: 0,
      },
    ],
    homePitchers: [
      {
        name: "Pfaadt",
        ip: "6.0",
        h: 5,
        r: 2,
        er: 2,
        bb: 1,
        k: 7,
        pitches: 92,
        hr: 0,
        era: "3.20",
        decision: "(W, 12-6)",
        strikes: 60,
        groundOuts: 5,
        flyOuts: 2,
        battersFaced: 24,
        inheritedRunners: 0,
        inheritedRunnersScored: 0,
      },
      {
        name: "Ginkel",
        ip: "1.0",
        h: 0,
        r: 0,
        er: 0,
        bb: 0,
        k: 2,
        pitches: 14,
        hr: 0,
        era: "2.80",
        decision: "(S, 18)",
        strikes: 9,
        groundOuts: 0,
        flyOuts: 1,
        battersFaced: 3,
        inheritedRunners: 1,
        inheritedRunnersScored: 0,
      },
    ],
    awayBattingNotes: [
      { label: "2B", value: "Carroll." },
      { label: "Team LOB", value: "6." },
    ],
    homeBattingNotes: [
      { label: "HR", value: "Freeman 2." },
      { label: "Team RISP", value: "2-for-5." },
    ],
    awayBaserunningNotes: [{ label: "SB", value: "Carroll." }],
    homeBaserunningNotes: [],
    awayFieldingNotes: [],
    homeFieldingNotes: [],
    awayPitchingTotals: {
      ip: "9.0",
      h: 9,
      r: 5,
      er: 5,
      bb: 3,
      k: 8,
      hr: 2,
      era: "5.00",
    },
    homePitchingTotals: {
      ip: "9.0",
      h: 8,
      r: 4,
      er: 4,
      bb: 2,
      k: 10,
      hr: 1,
      era: "4.00",
    },
  },
  teamStats: {
    away: {
      avg: ".245",
      obp: ".320",
      slg: ".410",
      hr: 0,
      r: 4,
      h: 8,
      k: 10,
      sb: 1,
      lob: 6,
      era: "4.50",
    },
    home: {
      avg: ".268",
      obp: ".335",
      slg: ".445",
      hr: 1,
      r: 5,
      h: 9,
      k: 8,
      sb: 0,
      lob: 4,
      era: "3.20",
    },
  },
  winProbability: null,
  hitChart: [
    {
      id: "h-final",
      team: "home",
      playerName: "Freeman",
      result: "hr",
      x: 0.55,
      y: 0.35,
    },
  ],
  sources: ["statsapi", "espn"],
  fetchedAt: "2026-08-03T03:00:00Z",
};

export const mlbScheduledDetail: MlbGameDetailView = {
  mlbGamePk: "824999",
  league: "mlb",
  status: "scheduled",
  statusLabel: "3:40 PM ET",
  gameDate: "2026-08-04",
  gameDateLabel: "Today",
  venue: "Citizens Bank Park",
  away: {
    id: "120",
    abbrev: "WSH",
    name: "Washington Nationals",
    score: null,
    record: "55-59",
    last10: "0-5",
    color: "#AB0003",
    logoUrl: null,
  },
  home: {
    id: "143",
    abbrev: "PHI",
    name: "Philadelphia Phillies",
    score: null,
    record: "60-53",
    last10: "3-2",
    color: "#E81828",
    logoUrl: null,
  },
  situation: null,
  linescore: null,
  plays: [],
  scoringPlays: [],
  boxScore: null,
  teamStats: null,
  winProbability: null,
  hitChart: [],
  decisions: null,
  sources: ["statsapi"],
  fetchedAt: "2026-08-04T00:00:00Z",
};
