import type { MlbGameDetailView } from "./types";

export const mlbLiveDetail: MlbGameDetailView = {
  mlbGamePk: "824971",
  league: "mlb",
  status: "live",
  statusLabel: "Top 3rd",
  venue: "Fenway Park",
  away: {
    id: "111",
    abbrev: "BOS",
    name: "Boston Red Sox",
    score: 2,
    color: "#BD3039",
    logoUrl: null,
  },
  home: {
    id: "119",
    abbrev: "LAD",
    name: "Los Angeles Dodgers",
    score: 1,
    color: "#005A9C",
    logoUrl: null,
  },
  linescore: {
    currentInning: 3,
    inningHalf: "top",
    innings: [
      { num: 1, awayRuns: 0, homeRuns: 1 },
      { num: 2, awayRuns: 1, homeRuns: 0 },
      { num: 3, awayRuns: 1, homeRuns: null },
    ],
    away: { runs: 2, hits: 3, errors: 0 },
    home: { runs: 1, hits: 2, errors: 1 },
  },
  situation: {
    balls: 2,
    strikes: 1,
    outs: 1,
    runners: { first: true, second: false, third: false },
    pitches: [
      {
        number: 1,
        type: "FF",
        mph: 95.2,
        result: "Ball",
        isStrike: false,
        zoneX: 0.1,
        zoneY: 0.2,
      },
      {
        number: 2,
        type: "SL",
        mph: 86.1,
        result: "Called Strike",
        isStrike: true,
        zoneX: -0.05,
        zoneY: 0.1,
      },
    ],
    atBat: {
      name: "Mookie Betts",
      hand: "RHB",
      summary: ".280 · 0-0 today",
    },
    onDeck: {
      name: "Freddie Freeman",
      hand: "LHB",
      summary: ".264",
    },
    pitching: {
      name: "Chris Sale",
      hand: "LHP",
      summary: "6 P · 0.1 IP, 0 ER, 6 K, 0 BB",
    },
    latestPlayText: "Ball",
  },
  plays: [
    {
      id: "p1",
      inning: 2,
      half: "bottom",
      text: "Ohtani grounds out",
      event: "Groundout",
      scoring: false,
      awayScore: 1,
      homeScore: 1,
    },
    {
      id: "p2",
      inning: 3,
      half: "top",
      text: "Betts singles",
      event: "Single",
      scoring: false,
      awayScore: 2,
      homeScore: 1,
    },
    {
      id: "p3",
      inning: 3,
      half: "top",
      text: "Freeman walks",
      event: "Walk",
      scoring: false,
      awayScore: 2,
      homeScore: 1,
    },
  ],
  scoringPlays: [
    {
      id: "s1",
      inning: 1,
      half: "bottom",
      text: "Freeman homers (1)",
      event: "HR",
      scoring: true,
      awayScore: 0,
      homeScore: 1,
    },
    {
      id: "s2",
      inning: 2,
      half: "top",
      text: "Devers doubles, Betts scores",
      event: "2B",
      scoring: true,
      awayScore: 1,
      homeScore: 1,
    },
  ],
  boxScore: {
    awayBatters: [
      {
        name: "Betts",
        position: "RF",
        order: 1,
        ab: 2,
        r: 1,
        h: 1,
        rbi: 0,
        bb: 0,
        so: 0,
      },
    ],
    homeBatters: [
      {
        name: "Freeman",
        position: "1B",
        order: 3,
        ab: 2,
        r: 1,
        h: 1,
        rbi: 1,
        bb: 0,
        so: 0,
      },
    ],
    awayPitchers: [],
    homePitchers: [
      {
        name: "Sale",
        ip: "2.1",
        h: 3,
        r: 2,
        er: 2,
        bb: 1,
        k: 3,
        pitches: 42,
      },
    ],
  },
  winProbability: {
    awayAbbrev: "BOS",
    homeAbbrev: "LAD",
    points: [{ playId: "p2", label: "Top 3", homeWinPct: 0.48 }],
    stakes: { label: "On this pitch", homeWinDelta: -2.1 },
  },
  hitChart: [],
  sources: ["statsapi", "espn"],
  fetchedAt: "2026-08-02T00:00:00Z",
};
